import { useEffect, useMemo, useState } from "react";
import { listOrganizations, listSites, listCohorts, restoreSession, signIn, type Organization, type OrganizationSite, type Cohort, type SaasSession } from "./saasApi";
import { calculatePreviewMetrics, createEvidenceBaseline, guessFieldMap, insertCommuteObservations, listEvidenceBaselines, lockEvidenceBaseline, normalizeCsvRows, parseCsv, type CsvFieldMap, type EvidenceBaseline, type ValidationIssue, type CommuteObservation } from "./evidenceApi";
import PccEvidenceDashboard from "./PccEvidenceDashboard";
import "./pcc-evidence-workbench.css";

const fields: { key: keyof CsvFieldMap; label: string; required?: boolean }[] = [
  { key:"participant_key",label:"Participant ID",required:true }, { key:"observation_date",label:"Observation date",required:true }, { key:"origin_zone",label:"Origin ZIP / zone" },
  { key:"commute_mode",label:"Commute mode",required:true }, { key:"one_way_miles",label:"One-way miles" }, { key:"vehicle_occupancy",label:"Vehicle occupancy" },
  { key:"remote_day",label:"Remote / telecommute" }, { key:"reported_to_site",label:"Reported to site" }, { key:"ev_hybrid_status",label:"EV / hybrid status" },
  { key:"parking_difficulty",label:"Parking difficulty" }, { key:"arrival_window",label:"Arrival window" }, { key:"departure_window",label:"Departure window" },
];

export default function PccEvidenceWorkbench() {
  const [session,setSession]=useState<SaasSession|null>(null); const [loading,setLoading]=useState(true); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState("");
  const [organizations,setOrganizations]=useState<Organization[]>([]); const [organizationId,setOrganizationId]=useState(""); const [sites,setSites]=useState<OrganizationSite[]>([]); const [cohorts,setCohorts]=useState<Cohort[]>([]);
  const [siteId,setSiteId]=useState(""); const [cohortId,setCohortId]=useState(""); const [baselines,setBaselines]=useState<EvidenceBaseline[]>([]); const [activeBaseline,setActiveBaseline]=useState<EvidenceBaseline|null>(null);
  const [baselineName,setBaselineName]=useState("PCC Commuter Baseline — Fall 2026"); const [start,setStart]=useState("2026-08-24"); const [end,setEnd]=useState("2026-09-06");
  const [headers,setHeaders]=useState<string[]>([]); const [rawRows,setRawRows]=useState<Record<string,string>[]>([]); const [map,setMap]=useState<CsvFieldMap|null>(null); const [normalized,setNormalized]=useState<CommuteObservation[]>([]); const [issues,setIssues]=useState<ValidationIssue[]>([]); const [excludeBlocking,setExcludeBlocking]=useState(false); const [notice,setNotice]=useState("");

  useEffect(()=>{restoreSession().then(s=>{setSession(s);setLoading(false)}).catch(()=>setLoading(false));},[]);
  useEffect(()=>{if(!session)return; listOrganizations(session).then(rows=>{setOrganizations(rows); if(!organizationId&&rows[0])setOrganizationId(rows[0].id)}).catch(e=>setError(String(e)));},[session]);
  useEffect(()=>{if(!session||!organizationId)return; Promise.all([listSites(session,organizationId),listCohorts(session,organizationId)]).then(([s,c])=>{setSites(s);setCohorts(c); if(!siteId&&s[0])setSiteId(s[0].id)}).catch(e=>setError(String(e)));},[session,organizationId]);
  useEffect(()=>{if(!session||!organizationId||!siteId)return; listEvidenceBaselines(session,organizationId,siteId).then(setBaselines).catch(()=>setBaselines([]));},[session,organizationId,siteId]);
  useEffect(()=>{if(!map||!activeBaseline||!organizationId||!siteId)return; const out=normalizeCsvRows({rawRows,fieldMap:map,organizationId,siteId,cohortId:cohortId||null,baselineId:activeBaseline.id}); setNormalized(out.rows);setIssues(out.issues);},[map,rawRows,activeBaseline,organizationId,siteId,cohortId]);

  const blocking=issues.filter(i=>i.severity==="blocking_error"); const warning=issues.filter(i=>i.severity==="warning");
  const rowsForImport=useMemo(()=>excludeBlocking?normalized.filter(r=>r.validation_status!=="blocking_error"):normalized,[normalized,excludeBlocking]); const preview=useMemo(()=>calculatePreviewMetrics(rowsForImport),[rowsForImport]);

  async function login(){setError("");try{setSession(await signIn(email.trim(),password));}catch(e){setError(e instanceof Error?e.message:String(e));}}
  async function makeBaseline(){if(!session||!organizationId||!siteId)return;setError("");try{const rows=await createEvidenceBaseline(session,{organization_id:organizationId,site_id:siteId,cohort_id:cohortId||null,name:baselineName,baseline_start:start,baseline_end:end});setActiveBaseline(rows[0]);setBaselines(await listEvidenceBaselines(session,organizationId,siteId));setNotice("Draft baseline created. Upload and validate commute records before locking.");}catch(e){setError(e instanceof Error?e.message:String(e));}}
  async function readFile(file:File){const text=await file.text();const parsed=parseCsv(text);setHeaders(parsed.headers);setRawRows(parsed.rows);setMap(guessFieldMap(parsed.headers));setNotice(`${parsed.rows.length} CSV rows loaded for field mapping and validation.`);}
  async function commitImport(){if(!session||!activeBaseline)return;if(blocking.length&&!excludeBlocking){setError("Resolve or explicitly exclude blocking rows before import.");return;}setError("");try{await insertCommuteObservations(session,rowsForImport);setNotice(`Imported ${rowsForImport.length} validated commute observations. ${blocking.length&&excludeBlocking?`${blocking.length} blocking rows were excluded.`:""}`);}catch(e){setError(e instanceof Error?e.message:String(e));}}
  async function lockBaseline(){if(!session||!activeBaseline)return;setError("");try{const locked=await lockEvidenceBaseline(session,activeBaseline.id);setActiveBaseline(locked);setNotice("Baseline locked. Future corrections should create a new baseline version instead of overwriting this snapshot.");}catch(e){setError(e instanceof Error?e.message:String(e));}}

  if(loading)return <div className="workbench-shell"><div className="workbench-card">Loading evidence workspace…</div></div>;
  if(!session)return <div className="workbench-shell"><section className="workbench-card auth"><p className="evidence-eyebrow">RELAY RIDER · EVIDENCE ADMIN</p><h1>Sign in to build a PCC baseline</h1><p>Authenticated organization membership and row-level security protect institutional commute records.</p><input value={email} onChange={e=>setEmail(e.currentTarget.value)} placeholder="Email" type="email"/><input value={password} onChange={e=>setPassword(e.currentTarget.value)} placeholder="Password" type="password"/><button onClick={login} disabled={!email||password.length<8}>Sign in</button>{error&&<div className="workbench-error">{error}</div>}</section></div>;

  return <div className="workbench-shell"><header className="workbench-top"><div><p className="evidence-eyebrow">RELAY RIDER · PCC EVIDENCE ENGINE</p><h1>Build a locked commuter baseline</h1><p>Import → normalize → validate → review → lock → compare later observations.</p></div><a href="?view=pcc-evidence">Public evidence view</a></header>
    {error&&<div className="workbench-error wide">{error}</div>}{notice&&<div className="workbench-notice">{notice}</div>}
    <section className="workbench-grid">
      <article className="workbench-card"><h2>1. Scope</h2><label>Organization<select value={organizationId} onChange={e=>{setOrganizationId(e.currentTarget.value);setSiteId("");setCohortId("");}}>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Site<select value={siteId} onChange={e=>setSiteId(e.currentTarget.value)}><option value="">Select site</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Cohort<select value={cohortId} onChange={e=>setCohortId(e.currentTarget.value)}><option value="">Site-wide cohort</option>{cohorts.filter(c=>!c.site_id||c.site_id===siteId).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></article>
      <article className="workbench-card"><h2>2. Baseline snapshot</h2><label>Name<input value={baselineName} onChange={e=>setBaselineName(e.currentTarget.value)}/></label><div className="date-pair"><label>Start<input type="date" value={start} onChange={e=>setStart(e.currentTarget.value)}/></label><label>End<input type="date" value={end} onChange={e=>setEnd(e.currentTarget.value)}/></label></div><button onClick={makeBaseline} disabled={!siteId||!baselineName||!start||!end}>Create draft baseline</button>{baselines.length>0&&<label>Existing baseline<select value={activeBaseline?.id??""} onChange={e=>setActiveBaseline(baselines.find(b=>b.id===e.currentTarget.value)??null)}><option value="">Select</option>{baselines.map(b=><option key={b.id} value={b.id}>{b.name} · {b.status}</option>)}</select></label>}</article>
    </section>

    <section className="workbench-card"><h2>3. Upload and map commute CSV</h2><input type="file" accept=".csv,text/csv" disabled={!activeBaseline||activeBaseline.status==="locked"} onChange={e=>e.currentTarget.files?.[0]&&readFile(e.currentTarget.files[0])}/>{headers.length>0&&map&&<div className="field-map">{fields.map(f=><label key={f.key}>{f.label}{f.required&&<b>*</b>}<select value={map[f.key]} onChange={e=>setMap({...map,[f.key]:e.currentTarget.value})}><option value="">Not mapped</option>{headers.map(h=><option key={h} value={h}>{h}</option>)}</select></label>)}</div>}</section>

    {normalized.length>0&&<><section className="workbench-grid metrics"><article className="workbench-card"><h2>4. Validation</h2><div className="metric-row"><span>Rows</span><b>{normalized.length}</b></div><div className="metric-row bad"><span>Blocking</span><b>{blocking.length}</b></div><div className="metric-row warn"><span>Warnings</span><b>{warning.length}</b></div><label className="checkbox"><input type="checkbox" checked={excludeBlocking} onChange={e=>setExcludeBlocking(e.currentTarget.checked)}/> Explicitly exclude blocking rows from this import</label></article><article className="workbench-card"><h2>5. Preliminary evidence preview</h2><div className="metric-row"><span>Participants</span><b>{preview.participantCount}</b></div><div className="metric-row"><span>Validated rows</span><b>{preview.validRows}</b></div><div className="metric-row"><span>Preview weekly VMT</span><b>{preview.weeklyVmt.toFixed(1)} mi</b></div><div className="metric-row"><span>Drive-alone row share</span><b>{preview.driveAloneShare.toFixed(1)}%</b></div><small>RR_VMT_METHOD_v0.1 preliminary research convention. Do not present as verified AQMD output.</small></article></section>
      <section className="workbench-card"><h2>Validation issues</h2>{issues.length?<div className="issue-table"><div className="issue-head"><span>Row</span><span>Participant</span><span>Severity</span><span>Issue</span></div>{issues.slice(0,100).map((i,idx)=><div key={`${i.row}-${i.code}-${idx}`}><span>{i.row}</span><span>{i.participantKey||"—"}</span><span className={i.severity}>{i.severity.replace("_"," ")}</span><span><b>{i.code}</b> · {i.message}</span></div>)}</div>:<p>No validation issues detected.</p>}<div className="workbench-actions"><button onClick={commitImport} disabled={!activeBaseline||activeBaseline.status==="locked"||(!excludeBlocking&&blocking.length>0)}>Import validated records</button><button className="secondary" onClick={lockBaseline} disabled={!activeBaseline||activeBaseline.status==="locked"||blocking.length>0}>Lock baseline</button></div></section></>}
    <section className="embedded-dashboard"><PccEvidenceDashboard /></section>
  </div>;
}
